<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assembly" nsURI="assembly" nsPrefix="assembly">
  <eClassifiers xsi:type="ecore:EClass" name="Assembly" eSuperTypes="componentModel.ecore#//ViewType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" upperBound="-1"
        eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" upperBound="-1"
        eType="#//AssemblyConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assembly" eType="#//Assembly"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedComponent"
        eType="ecore:EClass componentModel.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
        eType="#//RequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRoles" upperBound="-1"
        eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerComponent" eType="#//CompositeComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" eType="#//RequiredRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector" eSuperTypes="#//DelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" eType="#//RequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" eType="ecore:EClass componentModel.ecore#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="ecore:EClass componentModel.ecore#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector" eSuperTypes="#//DelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" eType="#//ProvidedRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
        eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" lowerBound="1"
        upperBound="-1" eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectors" lowerBound="1"
        upperBound="-1" eType="#//DelegationConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnectors" upperBound="-1"
        eType="#//AssemblyConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" lowerBound="1"
        upperBound="-1" eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulated" upperBound="-1"
        eType="#//AssemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//AssemblyContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" upperBound="-1"
        eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulated" upperBound="-1"
        eType="#//AssemblyContext"/>
  </eClassifiers>
</ecore:EPackage>
