<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="assembly" nsURI="assembly" nsPrefix="assembly">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="cm" value="componentModel.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext" eSuperTypes="#//Context componentModel.ecore#//AssemblyViewType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="reqInterfacesFromRequiredRoles providedInterfacesFromProvidedRoles onlyDelegationConnectorsIfComposite providedRoleForProvidedInterfaceExists requiredRoleForRequiredInterfaceExists"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="reqInterfacesFromRequiredRoles" value="self.requiredInterfaces = self.requiredRoles -> collect(interFace)"/>
      <details key="providedInterfacesFromProvidedRoles" value="self.providedInterfaces = self.providedRoles -> collect(interFace)"/>
      <details key="onlyDelegationConnectorsIfComposite" value="if self.instantiates.oclIsKindOf(CompositeComponent) &#xA;&#x9;&#x9;then self.delegationConnectors -> size() > 0 else self.delegationConnectors -> size() = 0 endif"/>
      <details key="providedRoleForProvidedInterfaceExists" value="if self.instantiates.oclIsKindOf(CompositeComponent) then &#xA;&#x9;&#x9;self.instantiates.oclAsType(CompositeComponent).encapsulatedAssemblyContexts -> collect(providedRoles) &#xA;&#x9;&#x9;-> forAll(role | self.providedInterfaces -> includes(role.interFace)) else true endif"/>
      <details key="requiredRoleForRequiredInterfaceExists" value="if self.instantiates.oclIsKindOf(CompositeComponent) then &#xA;&#x9;&#x9;self.instantiates.oclAsType(CompositeComponent).encapsulatedAssemblyContexts -> collect(requiredRoles) &#xA;&#x9;&#x9;-> forAll(role | self.requiredInterfaces -> includes(role.interFace)) else true endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiates" eType="ecore:EClass componentModel.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" ordered="false" upperBound="-1" eType="#//RequiredRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRoles" ordered="false" upperBound="-1" eType="#//ProvidedRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerComponent" eType="#//CompositeComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" ordered="false" upperBound="-1" eType="ecore:EClass componentModel.ecore#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="assemblyContextsNotEqual providedRoleHasRequiredInterface"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="assemblyContextsNotEqual" value="(not (self.providedRole.assemblyContext = self.requiredRole.assemblyContext)) = true"/>
      <details key="providedRoleHasRequiredInterface" value="self.providedRole.interFace = self.requiredRole.interFace"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole" lowerBound="1" eType="#//RequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector" eSuperTypes="#//DelegationConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="roleCanOnlyBeRequired"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="roleCanOnlyBeRequired" value="self.role.oclIsKindOf(RequiredRole)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//Role">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="requiredInterfaceFromServiceThatRequiresIt"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="requiredInterfaceFromServiceThatRequiresIt" value="self.assemblyContext.instantiates.interfaceServiceMap ->exists(entry | entry.services -> select(service| service.requiredInterfaces &#xA;&#x9;&#x9;-> includes(self.interFace)))  -> notEmpty() and not (self.assemblyContext.instantiates = null)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//Role">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="providededInterfaceFromISMap"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="providededInterfaceFromISMap" value="self.assemblyContext.instantiates.interfaceServiceMap ->exists(entry | entry.providedInterface = self.interFace)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interFace" eType="ecore:EClass componentModel.ecore#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector" eSuperTypes="#//DelegationConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="roleCanOnlyBeProvided"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="roleCanOnlyBeProvided" value="self.role.oclIsKindOf(ProvidedRole)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="contextIsPartOfOutwardAssemblyConnectors"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="contextIsPartOfOutwardAssemblyConnectors" value="&#xA;&#x9;&#x9;self.outwardAssemblyConnectors -> forAll(aCon | aCon.providedRole.assemblyContext = self xor aCon.requiredRole.assemblyContext = self )"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" ordered="false" upperBound="-1" eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectors" ordered="false" upperBound="-1" eType="#//DelegationConnector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedAssemblyConnectors" ordered="false" upperBound="-1" eType="#//AssemblyConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outwardAssemblyConnectors" ordered="false" upperBound="-1" eType="#//AssemblyConnector"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interFace" eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Context">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="providedRoleForProvidedInterfaceExists requiredRoleForRequiredInterfaceExists"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="providedRoleForProvidedInterfaceExists" value="&#xA;&#x9;&#x9;self.encapsulatedAssemblyContexts -> collect(providedRoles) -> forAll(role | providedInterfaces -> includes(role.interFace))"/>
      <details key="requiredRoleForRequiredInterfaceExists" value="&#xA;&#x9;&#x9;self.encapsulatedAssemblyContexts -> collect(requiredRoles) -> forAll(role | requiredInterfaces -> includes(role.interFace))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" ordered="false" lowerBound="1" upperBound="-1" eType="ecore:EClass componentModel.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedAssemblyContexts" ordered="false" upperBound="-1" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="componentModel.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedAssemblyContexts" ordered="false" upperBound="-1" eType="#//AssemblyContext"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextEnvironment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systems" ordered="false" upperBound="-1" eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeComponents" ordered="false" upperBound="-1" eType="#//CompositeComponent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContexts" upperBound="-1" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectors" ordered="false" upperBound="-1" eType="#//DelegationConnector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1" eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
