<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentModel" nsURI="componentModel" nsPrefix="cm">
  <eClassifiers xsi:type="ecore:EClass" name="SystemIndependentViewPoint" eSuperTypes="#//ViewPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//ViewType #//RepositoryViewType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="#//Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceeffectspecification"
        eType="#//ServiceEffectSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceServiceMap" upperBound="-1"
        eType="#//InterfaceServiceMapEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceServiceMapEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceEffectSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalCall" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
        eType="#//Signature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondence" lowerBound="1"
        upperBound="-1" eType="#//Signature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewPoint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewTypes" upperBound="-1"
        eType="#//ViewType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexParameterType" eSuperTypes="#//ParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleParameterType" abstract="true"
      eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//SimpleParameterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" lowerBound="1"
        eType="#//ParameterType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryViewType" abstract="true"
      eSuperTypes="#//ViewType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyViewTyp" eSuperTypes="#//ViewType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentViewTyp" eSuperTypes="#//ViewType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllocationViewType" eSuperTypes="#//ViewType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyViewPoint" eSuperTypes="#//ViewPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentViewPoint" eSuperTypes="#//ViewPoint"/>
</ecore:EPackage>
