<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentModel" nsURI="componentModel" nsPrefix="cm">
  <eClassifiers xsi:type="ecore:EClass" name="ViewPoint" instanceTypeName="ViewPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemIndependentViewPoint" eSuperTypes="#//ViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" upperBound="-1"
        eType="#//Repository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//ViewType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="#//Interface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulated" ordered="false"
        upperBound="-1" eType="#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceeffectspecification"
        eType="#//ServiceEffectSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceEffectSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
        eType="#//Signature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemSpecificViewpoint" eSuperTypes="#//ViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assembly" upperBound="-1"
        eType="#//Assembly"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assembly" eSuperTypes="#//ViewType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" upperBound="-1"
        eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" upperBound="-1"
        eType="#//AssemblyConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" eType="#//ProvidedRole"
        eOpposite="#//ProvidedRole/assemblycontext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" eType="#//RequiredRole"
        eOpposite="#//RequiredRole/assemblycontext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerComponent" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" eType="#//ProvidedRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" eType="#//RequiredRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" eType="#//RequiredRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerComponent" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondence" upperBound="-1"
        eType="#//Signature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" upperBound="-1"
        eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        upperBound="-1" eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" eType="#//AssemblyContext"
        eOpposite="#//AssemblyContext/requiredrole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" eType="#//AssemblyContext"
        eOpposite="#//AssemblyContext/providedrole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" eType="#//ProvidedRole"/>
  </eClassifiers>
</ecore:EPackage>
