<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="environment" nsURI="env" nsPrefix="env">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="assembly" value="assembly.ecore#/"/>
    <details key="cm" value="componentModel.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Environment" eSuperTypes="componentModel.ecore#//EnvironmentViewType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" ordered="false"
        upperBound="-1" eType="#//Container" containment="true" eKeys="#//Container/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" ordered="false" upperBound="-1"
        eType="#//Link" containment="true" eKeys="#//Link/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="containerPartOfOutwardLinks allocationOnSameContainerOrContainersLinked"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="containerPartOfOutwardLinks" value="&#xA;&#x9;&#x9;self.outwardLinks ->collect(container) -> includes(self)"/>
      <details key="allocationOnSameContainerOrContainersLinked" value="&#xA;&#x9;&#x9;let ProvidedAssemblyContexts =&#xA;&#x9;&#x9;self.allocationContexts -> collect(assemblyContext) -> collect(outwardAssemblyConnectors) -> collect(providedRole),&#xA;&#x9;&#x9;RequiredAssemblyContexts =&#xA;&#x9;&#x9;self.allocationContexts -> collect(assemblyContext) -> collect(outwardAssemblyConnectors) -> collect(requiredRole)&#xA;&#x9;&#x9;in self.allocationContexts -> collect(assemblyContext) -> includesAll(ProvidedAssemblyContexts -> union(RequiredAssemblyContexts))&#xA;&#x9;&#x9;xor self.outwardLinks ->exists(link | link.container ->collect(allocationContexts) -> collect(assemblyContext) &#xA;&#x9;&#x9;-> includesAll(ProvidedAssemblyContexts -> union(RequiredAssemblyContexts)))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContexts" ordered="false"
        upperBound="-1" eType="#//AllocationContext" containment="true" eOpposite="#//AllocationContext/container"
        eKeys="componentModel.ecore#//ViewType/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outwardLinks" ordered="false"
        upperBound="-1" eType="#//Link" eKeys="#//Link/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" ordered="false"
        lowerBound="2" upperBound="-1" eType="#//Container" eKeys="#//Container/name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="onlyTopLevelComponentsAllowedToBeAllocated"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="onlyTopLevelComponentsAllowedToBeAllocated" value="self.assemblyContext.ownerComponent = null"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" lowerBound="1"
        eType="ecore:EClass assembly.ecore#//AssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Container"
        eOpposite="#//Container/allocationContexts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocationEnvironment" eSuperTypes="componentModel.ecore#//AllocationViewType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContexts" ordered="false"
        upperBound="-1" eType="#//AllocationContext" containment="true" eKeys="#//AllocationContext/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteDeploymentViewPoint" eSuperTypes="componentModel.ecore#//DeploymentViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationEnvironment"
        eType="#//AllocationEnvironment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" eType="#//Environment"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
